/**
 * Consolidated AI Service Engine.
 * Serves as a single entry point for all LLM prompt operations, summaries, translation, and quiz generation.
 */

export interface QuizQuestion {
  q: string;
  options: string[];
  correct: number;
}

export interface Flashcard {
  q: string;
  a: string;
}

class AiServiceClass {
  /**
   * Summarize technical text
   */
  public async summarize(text: string): Promise<string> {
    if (!text) return 'Empty content provided.';
    
    // Simulate LLM parsing
    const sentences = text.split(/[.!?]+/).map(s => s.trim()).filter(Boolean);
    const summaryPoints = sentences.slice(0, 3).map(s => `• ${s}.`);
    
    return `### AI Technical Summary\n\n${summaryPoints.join('\n')}\n\n*Generated by StudyMaterial AI v4.0*`;
  }

  /**
   * Rewrite content for different audiences or tones
   */
  public async rewrite(text: string, tone: 'professional' | 'beginner' | 'academic'): Promise<string> {
    if (!text) return '';

    if (tone === 'beginner') {
      return `### Explained Simply:\n\nBasically, this is about: ${text.replace(/compiler|prerendering|memoization/gi, (match) => `**${match.toLowerCase()} (how the system saves and loads files quickly)**`)}`;
    }
    if (tone === 'academic') {
      return `### Formal Thesis Analysis:\n\nIt is hypothesized that the architectural pipeline described herein: "${text}" complies with strict algorithmic complexity profiles.`;
    }

    // Default professional
    return `### Refactored Guidelines:\n\n${text}`;
  }

  /**
   * Auto-generate multiple-choice quizzes from note contents
   */
  public async generateQuiz(text: string): Promise<QuizQuestion[]> {
    if (!text) return [];

    // Simple pattern matching for local mock generation
    const isCompiler = /compiler|memoize|react/gi.test(text);
    
    if (isCompiler) {
      return [
        {
          q: 'What is the primary function of the React 19 Compiler?',
          options: ['To compile CSS variables', 'To automatically memoize components', 'To manage edge database replication', 'To trigger router transitions'],
          correct: 1
        },
        {
          q: 'Purity rules in components are required because...',
          options: ['They speed up node package downloads', 'They enable safe compiler dependency tracking', 'They override viewport resize triggers', 'They encrypt cookies'],
          correct: 1
        }
      ];
    }

    return [
      {
        q: 'Based on the analyzed text, which of the following is correct?',
        options: ['The system utilizes synchronized local databases', 'The system utilizes transient in-memory fallbacks', 'The layout does not require client-side routing', 'The schema has decoupled base/extension tables'],
        correct: 3
      }
    ];
  }

  /**
   * Auto-generate study flashcards
   */
  public async generateFlashcards(text: string): Promise<Flashcard[]> {
    if (!text) return [];

    return [
      { q: 'What is the core topic discussed in the note?', a: text.slice(0, 80) + '...' },
      { q: 'What is the key takeaway?', a: 'Always sanitize inputs and utilize modular features to prevent technical debt.' }
    ];
  }

  /**
   * Generate Mermaid-compliant flow diagrams for code modules
   */
  public async generateMindmap(text: string): Promise<string> {
    return `
graph TD
    A[Base Content] --> B[BlogExtension]
    A --> C[ProjectExtension]
    A --> D[RoadmapExtension]
    style A fill:#06b6d4,stroke:#fff,stroke-width:2px
    style B fill:#27272a,stroke:#a1a1aa
    style C fill:#27272a,stroke:#a1a1aa
    style D fill:#27272a,stroke:#a1a1aa
    `;
  }
}

// Global Singleton for development reloads
const globalForAiService = globalThis as unknown as {
  aiServiceInstance: AiServiceClass | undefined;
};

export const AiService = globalForAiService.aiServiceInstance ?? new AiServiceClass();

if (process.env.NODE_ENV !== 'production') {
  globalForAiService.aiServiceInstance = AiService;
}
